services:
  flink-jobmanager:
    image: flink:1.20.2-scala_2.12
    container_name: flink-jobmanager
    hostname: flink-jobmanager
    restart: "no"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        state.checkpoints.dir: hdfs://namenode:8020/flink-checkpoints
    ports:
      - "8091:8081"
    networks:
      - bigdata-net

  flink-taskmanager1:
    image: flink:1.20.2-scala_2.12
    container_name: flink-taskmanager1
    hostname: flink-taskmanager1
    restart: "no"
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 2
        state.checkpoints.dir: hdfs://namenode:8020/flink-checkpoints
    depends_on:
      - flink-jobmanager
    networks:
      - bigdata-net

  flink-taskmanager2:
    image: flink:1.20.2-scala_2.12
    container_name: flink-taskmanager2
    hostname: flink-taskmanager2
    restart: "no"
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 2
        state.checkpoints.dir: hdfs://namenode:8020/flink-checkpoints
    depends_on:
      - flink-jobmanager
    networks:
      - bigdata-net

networks:
  bigdata-net:
    external: true